[package]
name = "vssetup"
version = "0.1.0"
authors = [
    "Heath Stewart <heaths@outlook.com>"
]
description = """
Utility classes for enumerating Microsoft Visual Studio setup instances.
"""
license = "MIT"
edition = "2018"
repository = "https://github.com/heaths/vssetup-rs"
categories = [
    "external-ffi-bindings",
    "os::windows-apis"
]
keywords = [
    "visual-studio"
]

[target.'cfg(windows)'.dependencies]
com = "^0.3.0"
winapi = { "version" = "^0.3.9", features = [ "oaidl", "oleauto", "winnt", "wtypes" ] }
