[package]
name = "bindings"
version = "0.1.0"
authors = [
    "Heath Stewart <heaths@outlook.com>"
]
license = "MIT"
edition = "2018"

[dependencies]
windows = "0.10.0"

[build-dependencies]
windows = "0.10.0"
