name: build

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          toolchain: stable
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: nightly
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: stable
          target: i686-pc-windows-msvc
        - os: windows-latest
          toolchain: nightly
          target: i686-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - name: update toolchain "${{ matrix.toolchain }}"
      run: rustup update --no-self-update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: install target "${{ matrix.target }}"
      run: rustup target add ${{ matrix.target }}
    - name: test
      run: cargo test --all --target ${{ matrix.target }}

  publish:
    runs-on: windows-latest
    if: ${{ github.event_name == "push" }}
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
