name: ci

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          toolchain: stable
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: nightly
          target: x86_64-pc-windows-msvc
        - os: windows-latest
          toolchain: stable
          target: i686-pc-windows-msvc
        - os: windows-latest
          toolchain: nightly
          target: i686-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - name: update toolchain '${{ matrix.toolchain }}'
      run: >
        rustup update --no-self-update ${{ matrix.toolchain }}
        && rustup default ${{ matrix.toolchain }}
    - name: install target '${{ matrix.target }}'
      run: rustup target add ${{ matrix.target }}
    - name: test
      run: cargo test --all --target ${{ matrix.target }}

  check:
    runs-on: windows-latest
    needs: test
    env:
      RUSTUP_TOOLCHAIN: stable
    steps:
    - uses: actions/checkout@v2
    - name: update toolchain '${{ env.RUSTUP_TOOLCHAIN }}'
      run: >
        rustup update --no-self-update ${{ env.RUSTUP_TOOLCHAIN }}
        && rustup default ${{ env.RUSTUP_TOOLCHAIN }}
    - name: check formatting
      run: cargo fmt --all -- --check
